In [2]:
# Installations of Libraries


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import plotly.express as px

In [7]:
a= np.array(range(1,21))

print(a)

b= np.zeros((3,3))
print(b)

c= np.ones((4,4))
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 1. Array Creation

a= np.array(range(1,21))
print(a)

print("\n")

b= np.zeros((3,3))
print(b)

print("\n")

c= np.ones((4,4,))
print(c)

In [ ]:
# Array Operations

a= np.array(range(1,6))
print(a)

print("\n")

b=np.array(range(21,26))
print(b)

print("\n")

c= a + b
print(c)

print("\n")

d = a - b
print(d)

print("\n")

e = a * b
print(e)

print("\n")

f = a / b
print(f)

print("\n")

g = a % b
print(g)

In [3]:
a=np.array(range(1,17))
print(a)

print("\n")


b=a.reshape((4,4))
print(b)

print("0th position of array is: ",b[0,:])

print("last position of array is: ",b[0,-1])

print("greater than 10:",b[b > 10])

print("factors by 2:",b[b % 2 == 0])

print("Middle 2 * 2 Matrix is :",b[1:3,1:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
0th position of array is:  [1 2 3 4]
last position of array is:  4
greater than 10: [11 12 13 14 15 16]
factors by 2: [ 2  4  6  8 10 12 14 16]
Middle 2 * 2 Matrix is : [[ 6  7]
 [10 11]]


In [4]:
# 6. Find Even Numbers
# Create NumPy array from 1–100 and extract only even numbers.

a = np.array(range(1, 101))
even_numbers = a[a % 2 == 0]
print("Even numbers from 1 to 100:", even_numbers)


Even numbers from 1 to 100: [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [5]:
# 7. Matrix Operations Perform: Matrix transpose Matrix multiplication Determinant Inverse on a 3x3 matrix.

matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                     [5, 6, 0]])

# Transpose
transpose = np.transpose(matrix)
print("Transpose of the matrix:\n", transpose)

# Matrix Multiplication (matrix multiplied by its transpose)
matrix_multiplication = np.dot(matrix, transpose)
print("Matrix multiplication (matrix * transpose):\n", matrix_multiplication)

# Determinant
determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", determinant)

# Inverse
inverse = np.linalg.inv(matrix)
print("Inverse of the matrix:\n", inverse)



Transpose of the matrix:
 [[1 0 5]
 [2 1 6]
 [3 4 0]]
Matrix multiplication (matrix * transpose):
 [[14 14 17]
 [14 17  6]
 [17  6 61]]
Determinant of the matrix: 0.9999999999999987
Inverse of the matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [6]:
# 8. Missing Value Handling Replace all NaN values in array with: Mean of array

array_with_nan = np.array([1, 2, np.nan, 4, 5])
mean_value = np.nanmean(array_with_nan)
array_without_nan = np.where(np.isnan(array_with_nan), mean_value, array_with_nan)
print("Array with NaN values:", array_with_nan)
print("Array after replacing NaN with mean:", array_without_nan)


Array with NaN values: [ 1.  2. nan  4.  5.]
Array after replacing NaN with mean: [1. 2. 3. 4. 5.]
